version: "3.7"

services:
  postgres:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - db
      - all

  nextjs:
    build: .
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - 3000:3000
    profiles:
      - all
    depends_on:
      - postgres

volumes:
  postgres-data:
