[build]
  command = "yarn generate && yarn build && yarn migrate"
  publish = "build"

[build.environment]
  POSTGRES_URI = "your_postgres_uri_here"

[functions]
  # your functions configuration here

[functions.environment]
  POSTGRES_URI = "your_postgres_uri_here"